# Reference document:
#   Red Hat Enterprise Linux 9
#   Confiburing and managing high availabillity clusters
#
#   https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html-single/configuring_and_managing_high_availability_clusters/index#assembly_configuring-quorum-devices-configuring-and-managing-high-availability-clusters
#
# Chapter 28. Configuring quorum devices

# 28.1. Installing quorum device packages
#
## # dnf install corosync-qdevice
#
- name: install qdevice package
  yum:
    name: 'corosync-qdevice'
    enablerepo: highavailability
    state: present

# 28.2. Configuring a quorum device
#
- set_fact:
#    QDEVICE_HOST: "{{ groups['qnetd'][0] }}"
    QDEVICE_ADDR: "{{ hostvars[groups['qnetd'][0]]['qnetd_addr'] }}"
  tags: always

# 3. authenticate user hacluster
#
## # pcs host auth QDEVICE -u hacluster -p PASSWORD
#
#  NOTE: addr= option does not work for qdevice on RHEL8.0 (at least)
#        needs to specify a same reachable address _both_ for
#        'pcs host auth' and 'pcs quorum device add'
#
#  WARN: password will be appeared on the command line. Be secure!
- name: authenticate user hacluster
  command: >
    pcs host auth
    {{ QDEVICE_ADDR }}
    -u hacluster -p {{ HACLUSTER_PASSWORD }}
  when: inventory_hostname == ansible_play_hosts[0]

# 4. Add the quorum device to the cluster
#
## # pcs quorum device add model net host=QDEVICE algorithm=ffsplit
#
- name: add the quorum device
  command: >
    pcs quorum device add model net host={{ QDEVICE_ADDR }} algorithm=ffsplit
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0 and "quorum device is already defined" not in result.stderr
  when: inventory_hostname == ansible_play_hosts[0]
  tags: qdevice-add
